# Generated by Django 5.1.15 on 2026-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('transportista', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('observacion_admin', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote_id', models.ForeignKey(db_column='lote_id', on_delete=django.db.models.deletion.CASCADE, to='produccion.lote')),
                ('of_id', models.ForeignKey(blank=True, db_column='of_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.ordenfabricacion')),
            ],
            options={
                'db_table': 'despachos',
            },
        ),
    ]
