# Generated by Django 5.1.15 on 2026-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='comprobante_saldo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_saldo/'),
        ),
    ]
