# Generated by Django 5.1.15 on 2026-05-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_add_comprobante_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='of_id',
        ),
    ]
