# Generated by Django 5.1.15 on 2026-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=50)),
                ('plazo_entrega', models.CharField(blank=True, default='', max_length=255)),
                ('equipo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(default='generado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_id', models.ForeignKey(db_column='of_id', on_delete=django.db.models.deletion.CASCADE, to='comercial.ordenfabricacion')),
            ],
            options={
                'db_table': 'pedidos_material',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='emitida', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_id', models.ForeignKey(db_column='of_id', on_delete=django.db.models.deletion.CASCADE, to='comercial.ordenfabricacion')),
                ('pm_id', models.ForeignKey(db_column='pm_id', on_delete=django.db.models.deletion.CASCADE, to='desarrollo.pedidomaterial')),
            ],
            options={
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='PedidoMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('descripcion', models.TextField()),
                ('uso_en', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('oc_fecha', models.CharField(blank=True, default='', max_length=50)),
                ('oc_id', models.ForeignKey(blank=True, db_column='oc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='desarrollo.ordencompra')),
                ('pedido_id', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='desarrollo.pedidomaterial')),
            ],
            options={
                'db_table': 'pedidos_material_items',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_tipo', models.CharField(max_length=100)),
                ('archivo_tamanio', models.IntegerField()),
                ('estado', models.CharField(default='enviado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_id', models.ForeignKey(db_column='of_id', on_delete=django.db.models.deletion.CASCADE, to='comercial.ordenfabricacion')),
            ],
            options={
                'db_table': 'planos',
            },
        ),
    ]
