# Generated by Django 5.1.15 on 2026-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='of_id',
        ),
        migrations.RunSQL(
            "ALTER TABLE pedidos_material ALTER COLUMN fecha DROP NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE pedidos_material SET fecha = NULL WHERE fecha = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE pedidos_material_items ALTER COLUMN oc_fecha DROP NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE pedidos_material_items SET oc_fecha = NULL WHERE oc_fecha = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='pedidomaterial',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomaterialitem',
            name='oc_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
