# Generated by Django 5.1.15 on 2026-05-06 11:34
# Portado de MariaDB a PostgreSQL para la app de práctica (cátedra app1):
#   - El SQL original usaba sintaxis MySQL-only (DROP FOREIGN KEY / MODIFY COLUMN) que
#     aborta `migrate` en PostgreSQL. Se reescribe con SQL portable.
#   - Se preservan EXACTAMENTE las mismas operaciones de ESTADO que el original
#     (of_id NO se quita del state acá: eso lo hace 0005; fecha/oc_fecha -> DateField),
#     para que 0004/0005/0006 sigan aplicando igual.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        # Drop FÍSICO de of_id en ordenes_compra (DB-only; el state del ORM lo limpia 0005).
        # En PostgreSQL, DROP COLUMN elimina automáticamente la FK que depende de la columna;
        # el DROP CONSTRAINT IF EXISTS previo es defensivo (el nombre lo genera Django igual en
        # ambos motores) y es no-op si no coincide.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_of_id_4fe23df4_fk_ordenes_fabricacion_id",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE ordenes_compra DROP COLUMN IF EXISTS of_id",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[],
        ),
        # fecha / oc_fecha: CharField -> DateField. AlterField genera el
        # `ALTER COLUMN ... TYPE date USING ...::date` en Postgres; en DB vacía
        # no hay filas que castear (los UPDATE de saneo del original ya no hacen falta).
        migrations.AlterField(
            model_name='pedidomaterial',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomaterialitem',
            name='oc_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
