# Generated by Django 5.1.15 on 2026-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ordenes_compra DROP FOREIGN KEY IF EXISTS ordenes_compra_of_id_4fe23df4_fk_ordenes_fabricacion_id",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE ordenes_compra DROP COLUMN IF EXISTS of_id",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE pedidos_material MODIFY COLUMN fecha DATE NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE pedidos_material SET fecha = NULL WHERE fecha = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE pedidos_material_items MODIFY COLUMN oc_fecha DATE NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE pedidos_material_items SET oc_fecha = NULL WHERE oc_fecha = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='pedidomaterial',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomaterialitem',
            name='oc_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
