# Generated by Django 5.1.15 on 2026-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_remove_ordencompra_of_id_alter_pedidomaterial_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
