# Generated by Django 5.1.15 on 2026-05-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0004_plano_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='of_id',
        ),
    ]
