# Generated by Django 5.1.15 on 2026-05-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0004_plano_archivo'),
    ]

    operations = [
        # La columna física ya fue eliminada por 0002 (RunSQL "DROP COLUMN IF EXISTS of_id").
        # Esta migración solo sincroniza el state del ORM, sin re-ejecutar el DROP,
        # para que el build desde cero sea reproducible (en prod quedó aplicada con --fake).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='ordencompra',
                    name='of_id',
                ),
            ],
            database_operations=[],
        ),
    ]
