# Generated by Django 5.1.15 on 2026-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('plazo_entrega', models.CharField(blank=True, default='', max_length=255)),
                ('monto_anticipo', models.FloatField(default=0.0)),
                ('moneda_anticipo', models.CharField(default='ARS', max_length=10)),
                ('anticipo_descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente_anticipo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ordenes_fabricacion',
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('monto_estimado', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('pagado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, default='')),
                ('factura_archivo', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_id', models.ForeignKey(db_column='of_id', on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='comercial.ordenfabricacion')),
            ],
            options={
                'db_table': 'anticipos',
            },
        ),
    ]
