# Generated by Django 5.1.15 on 2026-04-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticipo',
            name='cliente',
        ),
    ]
