# Generated by Django 5.1.15 on 2026-05-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_anticipo_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='plazo_anticipo_dias',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='responsable',
            field=models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_fabricacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
