# Generated by Django 5.1.15 on 2026-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_erp', '0005_bootstrap_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('administracion', 'Administración'), ('desarrollo', 'Desarrollo'), ('compras', 'Compras'), ('panol', 'Pañol'), ('produccion', 'Producción'), ('logistica', 'Logística'), ('gerencia', 'Gerencia'), ('soporte', 'Soporte de sistemas')], max_length=20),
        ),
    ]
