# Generated by Django 5.1.15 on 2026-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('planos_asociados', models.JSONField(blank=True, null=True)),
                ('movimientos_asociados', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(default='terminado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_id', models.ForeignKey(db_column='of_id', on_delete=django.db.models.deletion.CASCADE, to='comercial.ordenfabricacion')),
            ],
            options={
                'db_table': 'lotes',
            },
        ),
    ]
