# Generated by Django 5.1.15 on 2026-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_remove_ordencompra_of_id_alter_pedidomaterial_fecha_and_more'),
        ('panol', '0002_remove_movimientoitem_nombre_remove_stock_nombre_and_more'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='movimientos_asociados',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='planos_asociados',
        ),
        migrations.AddField(
            model_name='lote',
            name='movimientos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='panol.movimiento'),
        ),
        migrations.AddField(
            model_name='lote',
            name='planos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='desarrollo.plano'),
        ),
    ]
