# Generated by Django 5.1.15 on 2026-05-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0005_remove_ordencompra_of_id'),
        ('panol', '0001_initial'),
        ('produccion', '0003_lote_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='movimientos_asociados',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='planos_asociados',
        ),
        migrations.AddField(
            model_name='lote',
            name='movimientos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='panol.movimiento'),
        ),
        migrations.AddField(
            model_name='lote',
            name='planos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='desarrollo.plano'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(default='pre_produccion', max_length=50),
        ),
    ]
