# Generated by Django 5.1.15 on 2026-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, default='', max_length=255)),
                ('monto_total', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='registrada', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido_material_id', models.ForeignKey(db_column='pedido_material_id', on_delete=django.db.models.deletion.CASCADE, to='desarrollo.pedidomaterial')),
            ],
            options={
                'db_table': 'facturas_compra',
            },
        ),
        migrations.CreateModel(
            name='MaterialCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('unidad_medida', models.CharField(default='unidades', max_length=50)),
                ('proveedor', models.CharField(blank=True, default='', max_length=255)),
                ('factura_id', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='compras.facturacompra')),
            ],
            options={
                'db_table': 'materiales_compra',
            },
        ),
    ]
