# Generated by Django 5.1.15 on 2026-05-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desarrollo', '0002_remove_ordencompra_of_id_alter_pedidomaterial_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='registrada', max_length=50)),
                ('pdf_archivo', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido_material_id', models.ForeignKey(db_column='pedido_material_id', on_delete=django.db.models.deletion.CASCADE, to='desarrollo.pedidomaterial')),
            ],
            options={
                'db_table': 'facturas_compra',
            },
        ),
        migrations.CreateModel(
            name='MaterialCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('unidad_medida', models.CharField(default='unidades', max_length=50)),
                ('factura_id', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='compras.facturacompra')),
                ('insumo', models.ForeignKey(db_column='insumo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales_compra', to='compras.insumo')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_compra', to='compras.proveedor')),
            ],
            options={
                'db_table': 'materiales_compra',
            },
        ),
    ]
