# Generated by Django 5.1.15 on 2026-04-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='materialcompra',
            name='nombre',
        ),
        migrations.AddField(
            model_name='materialcompra',
            name='insumo',
            field=models.ForeignKey(db_column='insumo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales_compra', to='compras.insumo'),
        ),
        migrations.AlterField(
            model_name='materialcompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_compra', to='compras.proveedor'),
        ),
    ]
