# Generated by Django 5.1.15 on 2026-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='insumo',
            name='subcategoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(blank=True, default='u', max_length=20),
        ),
    ]
