# Generated by Django 5.1.15 on 2026-05-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0002_remove_anticipo_cliente'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='ingresado', max_length=50)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('verificacion_estado', models.CharField(default='conforme', max_length=50)),
                ('verificacion_notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura_id', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, to='compras.facturacompra')),
            ],
            options={
                'db_table': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='despachado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('of_id', models.ForeignKey(db_column='of_id', on_delete=django.db.models.deletion.CASCADE, to='comercial.ordenfabricacion')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(default='u', max_length=50)),
                ('insumo', models.ForeignKey(db_column='insumo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_items', to='compras.insumo')),
                ('movimiento_id', models.ForeignKey(db_column='movimiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='panol.movimiento')),
            ],
            options={
                'db_table': 'movimientos_items',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(default='u', max_length=50)),
                ('cantidad', models.FloatField(default=0.0)),
                ('insumo', models.OneToOneField(db_column='insumo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry', to='compras.insumo')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
