# Generated by Django 5.1.15 on 2026-04-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_facturacompra_proveedor_and_more'),
        ('panol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoitem',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='nombre',
        ),
        migrations.AddField(
            model_name='movimientoitem',
            name='insumo',
            field=models.ForeignKey(db_column='insumo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_items', to='compras.insumo'),
        ),
        migrations.AddField(
            model_name='stock',
            name='insumo',
            field=models.OneToOneField(db_column='insumo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry', to='compras.insumo'),
        ),
    ]
